-- =====================================================
-- V5: Create news_articles table and seed original content
-- Images map to: /assets/news/newsN.jpg|PNG
-- Content derived from original Angular project
-- =====================================================

CREATE TABLE news_articles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200)  NOT NULL,
    summary      VARCHAR(500),
    content      TEXT,
    image_url    VARCHAR(500),
    category     VARCHAR(50)   NOT NULL,
    publish_date DATE,
    author       VARCHAR(100),
    tags         VARCHAR(300),
    featured     BOOLEAN NOT NULL DEFAULT FALSE,
    published    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_news_category  ON news_articles(category);
CREATE INDEX idx_news_published ON news_articles(publish_date);
CREATE INDEX idx_news_featured  ON news_articles(featured);

-- =====================================================
-- Original news content from the Angular project
-- news1-8 images preserved from assets/news/
-- =====================================================

INSERT INTO news_articles (title, summary, content, image_url, category, publish_date, author, tags, featured, published)
VALUES (
    'Community Comes Together for Buffalo Rescue',
    'Pyaar Foundation receives heartfelt appreciation for their incredible work saving a buffalo in distress.',
    'I am really surprised to see the kind of work they are doing towards animals. The passion they possess towards caring for animals is like caring for one''s own child. Hats off to you guys for your work. Specially the life you have given to a buffalo today... you rock, keep doing the great work! — Diptish S. Dhongade, Community Member',
    '/assets/news/news1.jpg',
    'WELFARE_NEWS',
    CURRENT_DATE,
    'Pyaar Foundation',
    'rescue,buffalo,community,appreciation',
    TRUE,
    TRUE
);

INSERT INTO news_articles (title, summary, content, image_url, category, publish_date, author, tags, featured, published)
VALUES (
    'Stray Animal Welfare Drive — Vaccination Camp',
    'Volunteers organized a free vaccination camp for stray animals across the city.',
    'Our team of dedicated volunteers conducted a free vaccination drive covering over 50 stray animals. Every vaccinated animal is a step towards a healthier community for both animals and people.',
    '/assets/news/news2.PNG',
    'CAMPAIGN',
    CURRENT_DATE,
    'Animal Welfare Team',
    'vaccination,camp,stray,health',
    TRUE,
    TRUE
);

INSERT INTO news_articles (title, summary, content, image_url, category, publish_date, author, tags, featured, published)
VALUES (
    'Adoption Success Story — Bruno Finds His Forever Home',
    'Bruno, a Labrador rescued from the streets, has found a loving family after 3 months on the platform.',
    'After being posted on our platform by a caring volunteer, Bruno the Labrador spent 3 months waiting for his forever family. Last week, a family from Mumbai adopted him and the transformation has been remarkable. Bruno is now living his best life with children who adore him.',
    '/assets/news/news3.PNG',
    'SUCCESS_STORY',
    CURRENT_DATE,
    'Platform Team',
    'adoption,labrador,dog,success',
    FALSE,
    TRUE
);

INSERT INTO news_articles (title, summary, content, image_url, category, publish_date, author, tags, featured, published)
VALUES (
    'NGO Partnership Announcement — Expanding Rescue Network',
    'Animal Welfare and Wellness partners with three new NGOs to expand our rescue coverage.',
    'We are thrilled to announce partnerships with three dedicated animal welfare NGOs across Maharashtra, Karnataka, and Delhi. This collaboration will allow us to rescue and rehome significantly more animals while maintaining the highest standards of animal care.',
    '/assets/news/news4.PNG',
    'NGO_UPDATE',
    CURRENT_DATE,
    'Platform Admin',
    'ngo,partnership,rescue,expansion',
    FALSE,
    TRUE
);

INSERT INTO news_articles (title, summary, content, image_url, category, publish_date, author, tags, featured, published)
VALUES (
    'Awareness Campaign — Understanding Stray Animal Needs',
    'A photo series highlighting the daily lives of stray animals and what they truly need from us.',
    'Stray animals face unique challenges — from finding food and water to avoiding traffic and disease. Our latest awareness campaign documents a week in the life of street animals and educates communities on responsible, compassionate coexistence.',
    '/assets/news/news5.PNG',
    'CAMPAIGN',
    CURRENT_DATE,
    'Volunteer Team',
    'awareness,stray,education,community',
    FALSE,
    TRUE
);

INSERT INTO news_articles (title, summary, content, image_url, category, publish_date, author, tags, featured, published)
VALUES (
    'World Animal Day — Celebration and Pledge Drive',
    'Our community celebrated World Animal Day with a pledge drive committing to responsible pet ownership.',
    'On World Animal Day, hundreds of community members joined our pledge drive committing to report stray animals, feed responsibly, and support adoption over buying. The event brought together families, students, and animal lovers in a shared commitment to animal welfare.',
    '/assets/news/news6.PNG',
    'WELFARE_NEWS',
    CURRENT_DATE,
    'Events Team',
    'world-animal-day,pledge,celebration,community',
    TRUE,
    TRUE
);

INSERT INTO news_articles (title, summary, content, image_url, category, publish_date, author, tags, featured, published)
VALUES (
    'Rescue Operation — 5 Kittens Saved from Flood-Affected Area',
    'Volunteers braved difficult conditions to rescue five kittens from a flooded locality.',
    'Following heavy rains, five kittens were found trapped in a flooded area. Our rescue team, in coordination with local authorities, successfully rescued all five. They are currently in foster care and will be ready for adoption once fully healthy.',
    '/assets/news/news7.PNG',
    'WELFARE_NEWS',
    CURRENT_DATE,
    'Rescue Team',
    'rescue,cats,kittens,flood,emergency',
    FALSE,
    TRUE
);

INSERT INTO news_articles (title, summary, content, image_url, category, publish_date, author, tags, featured, published)
VALUES (
    'Volunteer Spotlight — A Year of Compassionate Service',
    'Celebrating our volunteers who have made extraordinary contributions to animal welfare this year.',
    'This year, our volunteer community grew to over 200 active members who collectively contributed 5,000+ hours to animal rescue, care, and adoption facilitation. We celebrate their dedication and compassion that makes this platform possible.',
    '/assets/news/news8.jpg',
    'NGO_UPDATE',
    CURRENT_DATE,
    'Community Manager',
    'volunteers,appreciation,milestone,community',
    FALSE,
    TRUE
);

-- =====================================================
-- Update animal records to link existing images
-- Maps original list_adopt.json -> real assets
-- =====================================================

-- Link stray animal images (inserted in V4)
-- Animals were inserted in order: Bruno, Whiskers, Max
-- Add images referencing actual asset files

INSERT INTO animal_images (animal_id, image_url, public_id, is_primary, display_order)
SELECT id, '/assets/stray_animals/stray1.jpg', 'local/stray1', true, 0
FROM animals WHERE name = 'Bruno' LIMIT 1;

INSERT INTO animal_images (animal_id, image_url, public_id, is_primary, display_order)
SELECT id, '/assets/stray_animals/stray5.jpg', 'local/stray5', true, 0
FROM animals WHERE name = 'Whiskers' LIMIT 1;

INSERT INTO animal_images (animal_id, image_url, public_id, is_primary, display_order)
SELECT id, '/assets/stray_animals/stray2.jpg', 'local/stray2', true, 0
FROM animals WHERE name = 'Max' LIMIT 1;
