-- =====================================================
-- V2: Create animals and animal_images tables
-- =====================================================

CREATE TABLE animals (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100),
    category       VARCHAR(50)  NOT NULL,
    breed          VARCHAR(100),
    age_months     INTEGER,
    gender         VARCHAR(10),
    color          VARCHAR(100),
    location       VARCHAR(255) NOT NULL,
    description    VARCHAR(2000),
    health_status  VARCHAR(100),
    vaccinated     BOOLEAN      NOT NULL DEFAULT FALSE,
    neutered       BOOLEAN      NOT NULL DEFAULT FALSE,
    status         VARCHAR(30)  NOT NULL DEFAULT 'AVAILABLE',
    posted_by_id   BIGINT       NOT NULL REFERENCES users(id),
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE animal_images (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id    BIGINT       NOT NULL REFERENCES animals(id) ON DELETE CASCADE,
    image_url    VARCHAR(500) NOT NULL,
    public_id    VARCHAR(255),
    is_primary   BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER     NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX idx_animals_status    ON animals(status);
CREATE INDEX idx_animals_category  ON animals(category);
CREATE INDEX idx_animals_location  ON animals(location);
CREATE INDEX idx_animals_posted_by ON animals(posted_by_id);
CREATE INDEX idx_animal_images     ON animal_images(animal_id);
