-- =====================================================
-- V3: Create adoption_requests table
-- Full adoption workflow with approval/rejection
-- =====================================================

CREATE TABLE adoption_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id     BIGINT       NOT NULL REFERENCES animals(id),
    requester_id  BIGINT       NOT NULL REFERENCES users(id),
    status        VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    message       VARCHAR(1000),
    reviewer_id   BIGINT       REFERENCES users(id),
    review_note   VARCHAR(500),
    reviewed_at   TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_adoption_animal    ON adoption_requests(animal_id);
CREATE INDEX idx_adoption_requester ON adoption_requests(requester_id);
CREATE INDEX idx_adoption_status    ON adoption_requests(status);
